### ISSUE TITLE
Comparación entre lenguajes con diferente tipo de tipado

### ISSUE THREAD

**Issue by carlosnufe** [GersonLazaro/aprende-x-si-sabes-y#12]
Buenas, 

Después de revisar este repositorio me gustaría añadir que hay veces que no es posible comparar dos lenguajes con diferente _tipado_ y al realizarlo, el posible lector con desconocimiento sobre el lenguaje a aprender (objetivo de este proyecto) puede presentarse frente a un caso que no corresponde fielmente a lo que expone la comparación. 

Uno de los ejemplos puede ser **Java** comparado con **Javascript**. En la web se expone el ejemplo de los arreglos y vectores en el que en el lenguaje _tipado_ requiere que la declaración cumpla un tipo de datos dentro del arreglo o vector. Sin embargo, en el caso de Javascript no es del mismo modo, pues los datos que se almacenan pueden ser de cualquier tipo ya que en este aspecto Javascript tiene ésta flexibilidad. 

Una opción para mejorar este de cara al lector sería desarrollar un pequeño script que en base al lenguaje X rellenara el selector con los lenguajes posible a comparar fielmente. 

Otra opción más compleja, sería desarrollar un script en el que el se establecería una relación entre lenguaje X y lenguaje Y y sus posibles ejemplos a comparar.

**Comment by GersonLazaro** [comment]
Hola @carlosnufe 
El sitio está actualmente en un estado muy inicial (lo inicié el sábado anterior) y hay varios puntos por mejorar seriamente (Por ejemplo, el método de lectura de los archivos desde el repositorio no es para nada óptimo, la forma de mostrar los ejemplos se hará muy incomoda al usuario cuando el repositorio crezca y para cada par de lenguaje tenga una página con un scroll interminable, entre otros). De momento es una especie de producto mínimo viable, y dado que está teniendo buena acogida, hay que seguir mejorándolo y puliéndolo.

En lo que mencionas tienes toda la razón y la segunda idea (la que mencionas como mas compleja) me gusta bastante, y pensaría que es el camino a seguir. 

En unos días estaré planificando mejoras, entre esas las que expliqué mas arriba, y la que tu mencionas. Estaré avisando. Tal vez temporalmente sea útil indicar estas cosas como comentario de código en los propios ejemplos, mientras se implementa una solución al respecto.

Muchas gracias por la idea, había pasado por alto ese detalle pero es algo bastante importante.

:+1:

**Comment by carlosnufe** [comment]
Closed due to inactivity.
