### ISSUE TITLE
Añadir ejemplo de loops en Java y Python

### ISSUE THREAD

**Issue by TefiC** [GersonLazaro/aprende-x-si-sabes-y#23]
Buenos días, creé  estos ejemplos de loops en Java y Python que podrían ser incorporados al proyecto

**JAVA**

```
String[] animales = new String[]{"perro", "elefante", "leopardo"};

for(String animal : animales) {
	System.out.println(animal);
}
```
 **PYTHON**
```
animales = ["perro", "elefante", "leopardo"]
for animal in animales:
	print(animal)
```

**Comment by GersonLazaro** [comment]
Hola @TefiC 
Gracias por los ejemplos. ¿Los agregas al repositorio o los agrego yo?
Recuerda que si los agregas puedes participar en [Hacktoberfest](http://hacktoberfest.digitalocean.com/). De lo contrario me avisas para incorporarlos pronto. 

Saludos :smile:

**Comment by TefiC** [comment]
Hola @GersonLazaro , me gustaría agregarlos al proyecto 😄 Voy a enviar un pull request con los cambios.  

Muchas gracias,
Saludos.

**Comment by TefiC** [comment]
Hola @GersonLazaro , por favor ¿podría indicarme en qué archivo debería incluir los ejemplos? Se ha añadido una categoría para bucles for-each y estos ejemplos pertenecen a esa categoría. ¿Debería añadirlos en el mismo archivo "for-each-loop" bajo el ejemplo existente? Gracias. He enviado un pull request con el ejemplo existente de for-each loop (originalmente en Javascript) en Java #25

**Comment by GersonLazaro** [comment]
Hola @TefiC.

Acabo de integrar el Pull Request de java :smile: 
El ejemplo en Python aún no ha sido integrado, por lo que podrías agregar un archivo similar a la carpeta de Python.

**Comment by TefiC** [comment]
😄 @GersonLazaro Ok, gracias. Voy a enviar un pull request con el mismo ejemplo en Python.

**Comment by TefiC** [comment]
Buenos días, envié el pull request #27 con el ejemplo en Python.

**Comment by GersonLazaro** [comment]
Gracias. Aprobado :smiley:
